### ISSUE TITLE
Alt tag support

### ISSUE THREAD

**Issue by bollig** [aws-samples/aws-parallelcluster-post-install-scripts#31]
https://github.com/aws-samples/aws-parallelcluster-post-install-scripts/blob/f1eededcdc6fb548515c32880beb186d2fd53766/nccl/postinstall.sh#L11

This clone command does not fetch all tags. Either update line 10 to `git clone --depth=1 --branch "${NCCL_VERSION}" https://github.com/NVIDIA/nccl.git /opt/nccl  && cd $_` and delete line 11, or insert `git fetch --tags` ahead of line 11.

**Comment by mhuguesaws** [comment]
Addressed in #26
