### ISSUE TITLE
AWS Parallel cluster cookbook overrides the '/etc/sysconfig/slurmd'

### ISSUE THREAD

**Issue by hdyaro88** [aws-samples/aws-parallelcluster-post-install-scripts#48]
Setting the PATH variable this way is of no use as the file ***'/etc/sysconfig/slurmd'*** is getting overridden by AWS parallel cookbook.

https://github.com/aws-samples/aws-parallelcluster-post-install-scripts/blob/6557b15add8936e1a6a572d48fec98236e368947/pyxis/postinstall.sh#L104

***Logs from the chef-client***

```
Recipe: aws-parallelcluster-slurm::finalize_compute
  * ruby_block[get_compute_nodename] action run[2024-09-23T11:57:55+00:00] INFO: Processing ruby_block[get_compute_nodename] action run (aws-parallelcluster-slurm::finalize_compute line 18)
[2024-09-23T11:57:55+00:00] INFO: ruby_block[get_compute_nodename] called

    - execute the ruby block get_compute_nodename
  * directory[/etc/sysconfig] action create[2024-09-23T11:57:55+00:00] INFO: Processing directory[/etc/sysconfig] action create (aws-parallelcluster-slurm::finalize_compute line 24)
 (up to date)
  * template[/etc/sysconfig/slurmd] action create[2024-09-23T11:57:55+00:00] INFO: Processing template[/etc/sysconfig/slurmd] action create (aws-parallelcluster-slurm::finalize_compute line 30)
[2024-09-23T11:57:55+00:00] INFO: template[/etc/sysconfig/slurmd] backed up to /etc/chef/local-mode-cache/backup/etc/sysconfig/slurmd.chef-20240923115755.424304
[2024-09-23T11:57:55+00:00] INFO: template[/etc/sysconfig/slurmd] updated file contents /etc/sysconfig/slurmd

    - update content in file /etc/sysconfig/slurmd from b509b2 to 4102f2
    --- /etc/sysconfig/slurmd	2024-09-23 11:57:50.121045146 +0000
    +++ /etc/sysconfig/.chef-slurmd20240923-5316-n97ta9	2024-09-23 11:57:55.413026966 +0000
    @@ -1,4 +1,2 @@
    -PATH=/opt/slurm/sbin:/opt/slurm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
    +SLURMD_OPTIONS='-N gpu-queue-st-worker-node-1'
```

This recipe has a finalize task which runs after all the post-install scripts , and that task uses a template for creating the  '/etc/sysconfig/slurmd' 

**Template Link**: https://github.com/aws/aws-parallelcluster-cookbook/blob/develop/cookbooks/aws-parallelcluster-slurm/templates/default/compute_node_finalize/slurm/slurm.sysconfig.erb

**Task Link**:  https://github.com/aws/aws-parallelcluster-cookbook/blob/develop/cookbooks/aws-parallelcluster-slurm/recipes/finalize/finalize_compute.rb#L30

**Q.** How did i verify that it is actually overriding ? 
**A**: Before overriding it creates a backup file, the backup file has the PATH variable which is being set in the pyxis post install scripts , this can be verify from the logs above as well .

**Comment by mhuguesaws** [comment]
Thank you for reporting and your analysis.
We are working on a fix.

**Comment by hdyaro88** [comment]
Thank you for the quick fix! I had implemented a similar workaround, but I was waiting for an official update. I really appreciate your effort.
