### ISSUE TITLE
Add ECR auth example

### ISSUE THREAD

**Issue by lipovsek-aws** [aws-samples/aws-parallelcluster-post-install-scripts#9]
ECR is [now supported](https://github.com/NVIDIA/enroot/pull/159) lets add it to default template.

**Comment by mhuguesaws** [comment]
Will have to create `/enroot/.credentials` to authenticate against ECR.

Example of `.credentials`:

```text
machine 159553542841.dkr.ecr.us-west-2.amazonaws.com login AWS password $(aws ecr get-login-password --region us-west-2)
```

enroot import docker://159553542841.dkr.ecr.us-west-2.amazonaws.com/nccl-tests:efa1.34.0-ofiv1.11.0-aws-ncclv2.23.4-1-testsv2.13.10
